configName: pic32cm_jh01_curiosity_pro
folderName: ''
format_version: v1.0
frameworkPath: ../../../../..
processor: PIC32CM5164JH01100
projectName: ''
settings:
  PackageFilter: bsp;core;csp;usb;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32CM-JH_DFP\1.0.31\PIC32CM-JH00\atdf\PIC32CM5164JH01100.atdf
