configName: pic32cm_jh01_curiosity_pro
folderName: ''
format_version: v1.0
frameworkPath: ../../../../..
processor: PIC32CM5164JH01100
projectName: ''
settings:
  PackageFilter: bootloader;bootloader_apps_i2c;bootloader_apps_usb;bsp;core;core_apps_pic32cm_jh00_jh01;core_apps_sam_g55;csp;csp_apps_pic32cm_jh00_jh01;csp_apps_pic32cm_mc00;csp_apps_pic32mk;csp_apps_pic32mx;csp_apps_pic32mz_ef;csp_apps_sam_d10;csp_apps_sam_d11;csp_apps_sam_d20;csp_apps_sam_d21_da1;csp_apps_sam_g55;csp_apps_sam_ha1;usb;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32CM-JH_DFP\1.0.59\PIC32CM-JH00\atdf\PIC32CM5164JH01100.atdf
