format_version: v1.0
type: UniqueComponent
attributes: {id: rtc}
children:
- type: Symbols
  children:
  - type: Hex
    attributes: {id: RTC_MODE0_TIMER_COMPARE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '4096'}
- type: ElementPosition
  attributes: {x: '170', y: '80', id: rtc}
