configName: pic32cm_jh01_cpro
folderName: pic32cm_jh01_cpro
format_version: v1.0
frameworkPath: ..\..\..\HF
processor: PIC32CM5164JH01100
projectName: nvmctrl_ecc_testing_pic32cm_jh01_cpro
settings:
  PackageFilter: bootloader;bsp;cec173x_soteria_lib;core;crypto;csp;Devices;dev_packs;harmony-services;net;quick_docs
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32CM-JH_DFP\1.0.80\PIC32CM-JH01\atdf\PIC32CM5164JH01100.atdf
