files:
- generatedChecksum: 9762B12622FD08815784244AF2080753
  logicalPath: config\pic32cm_jh01_curiosity_pro
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 9762B12622FD08815784244AF2080753
- generatedChecksum: 07B86D0D82F4D28399AA9490F87DB3D0
  logicalPath: config\pic32cm_jh01_curiosity_pro
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 07B86D0D82F4D28399AA9490F87DB3D0
- generatedChecksum: 8D708A3B930BF80939B3322E4EEEE5BE
  logicalPath: config\pic32cm_jh01_curiosity_pro
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 8D708A3B930BF80939B3322E4EEEE5BE
- generatedChecksum: 328F1E09E0DD9BEE901C4562A3E5180A
  logicalPath: config\pic32cm_jh01_curiosity_pro
  name: libc_syscalls.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 328F1E09E0DD9BEE901C4562A3E5180A
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 90D14AFE17D024F70B51581FFF357008
  logicalPath: config\pic32cm_jh01_curiosity_pro\peripheral\clock
  name: plib_clock.c
  physicalPath: peripheral\clock
  security: NON_SECURE
  type: SOURCE
  userChecksum: 90D14AFE17D024F70B51581FFF357008
- generatedChecksum: C99E6D9B9BA371EA749B7DC16BC2C209
  logicalPath: config\pic32cm_jh01_curiosity_pro\peripheral\evsys
  name: plib_evsys.c
  physicalPath: peripheral\evsys
  security: NON_SECURE
  type: SOURCE
  userChecksum: C99E6D9B9BA371EA749B7DC16BC2C209
- generatedChecksum: 6B223F9D652989C89A527F18FDF95008
  logicalPath: config\pic32cm_jh01_curiosity_pro\peripheral\nvic
  name: plib_nvic.c
  physicalPath: peripheral\nvic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 6B223F9D652989C89A527F18FDF95008
- generatedChecksum: 6199352E96A4D76EB273FD2BA42D39B4
  logicalPath: config\pic32cm_jh01_curiosity_pro\peripheral\nvmctrl
  name: plib_nvmctrl.c
  physicalPath: peripheral\nvmctrl
  security: NON_SECURE
  type: SOURCE
  userChecksum: 6199352E96A4D76EB273FD2BA42D39B4
- generatedChecksum: D304B3E298308F8ADF398C8F656CDB6F
  logicalPath: config\pic32cm_jh01_curiosity_pro\peripheral\port
  name: plib_port.c
  physicalPath: peripheral\port
  security: NON_SECURE
  type: SOURCE
  userChecksum: D304B3E298308F8ADF398C8F656CDB6F
- generatedChecksum: D9068F6C5888E113723C77B68CB00455
  logicalPath: config\pic32cm_jh01_curiosity_pro\peripheral\sercom\usart
  name: plib_sercom4_usart.c
  physicalPath: peripheral\sercom\usart
  security: NON_SECURE
  type: SOURCE
  userChecksum: D9068F6C5888E113723C77B68CB00455
- generatedChecksum: AC6B76578B7F3AB21F42ABB85DA71201
  logicalPath: config\pic32cm_jh01_curiosity_pro\peripheral\systick
  name: plib_systick.c
  physicalPath: peripheral\systick
  security: NON_SECURE
  type: SOURCE
  userChecksum: AC6B76578B7F3AB21F42ABB85DA71201
- generatedChecksum: 949BBD944EC8B81E639121B72E7C7510
  logicalPath: config\pic32cm_jh01_curiosity_pro
  name: startup_xc32.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 949BBD944EC8B81E639121B72E7C7510
- generatedChecksum: D421C89FB241284CA1B201213896DDEC
  logicalPath: config\pic32cm_jh01_curiosity_pro\stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: D421C89FB241284CA1B201213896DDEC
- generatedChecksum: ABB8A9B29E96D33CDF162694A41E6F6A
  logicalPath: packs\PIC32CM5164JH01100_DFP\component
  name: ac.h
  physicalPath: ..\..\packs\PIC32CM5164JH01100_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: ABB8A9B29E96D33CDF162694A41E6F6A
- generatedChecksum: 5C2DF37B31D9D156332536EC9E67FBDA
  logicalPath: packs\PIC32CM5164JH01100_DFP\component
  name: adc.h
  physicalPath: ..\..\packs\PIC32CM5164JH01100_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 5C2DF37B31D9D156332536EC9E67FBDA
- generatedChecksum: 01B82424BC59A54620F7E9E0DB808EBB
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cachel1_armv7.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 01B82424BC59A54620F7E9E0DB808EBB
- generatedChecksum: 10CACE6DF225988577C9F1B9675803F3
  logicalPath: packs\PIC32CM5164JH01100_DFP\component
  name: can.h
  physicalPath: ..\..\packs\PIC32CM5164JH01100_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 10CACE6DF225988577C9F1B9675803F3
- generatedChecksum: 48512ABF7917CCE6B03A81DDE403FF5F
  logicalPath: packs\PIC32CM5164JH01100_DFP\component
  name: ccl.h
  physicalPath: ..\..\packs\PIC32CM5164JH01100_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 48512ABF7917CCE6B03A81DDE403FF5F
- generatedChecksum: 00A88E28C299A373117BC4D5B9E80C80
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_armcc.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 00A88E28C299A373117BC4D5B9E80C80
- generatedChecksum: 734DF6998F09B2D22A4D9FE1D544FDFC
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_armclang.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 734DF6998F09B2D22A4D9FE1D544FDFC
- generatedChecksum: 5D653BEFE5E6B1D00AB3682CE5D24C11
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_armclang_ltm.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 5D653BEFE5E6B1D00AB3682CE5D24C11
- generatedChecksum: 60385A5C6C9882B5D30709A1F6EAEC35
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_compiler.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 60385A5C6C9882B5D30709A1F6EAEC35
- generatedChecksum: 42E8B722917508A3A9373D13AD827ED6
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_gcc.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 42E8B722917508A3A9373D13AD827ED6
- generatedChecksum: 376D5C7FD29CAA507ACB1AAB8746B1AD
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_iccarm.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 376D5C7FD29CAA507ACB1AAB8746B1AD
- generatedChecksum: 52F91AC0727F2311EDA0E3BAA7719A9F
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_version.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 52F91AC0727F2311EDA0E3BAA7719A9F
- generatedChecksum: CCBD23918BE14943EA128B0D552031C5
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: core_cm0plus.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: CCBD23918BE14943EA128B0D552031C5
- generatedChecksum: D6F783D0D78F5AEAF270501B0DB713C4
  logicalPath: packs\PIC32CM5164JH01100_DFP\component
  name: dac.h
  physicalPath: ..\..\packs\PIC32CM5164JH01100_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: D6F783D0D78F5AEAF270501B0DB713C4
- generatedChecksum: 72C102FA4134101EC39D51C6E152FC58
  logicalPath: config\pic32cm_jh01_curiosity_pro
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 72C102FA4134101EC39D51C6E152FC58
- generatedChecksum: B66ED4F8E597EC93221FF19E53EF292C
  logicalPath: config\pic32cm_jh01_curiosity_pro
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: B66ED4F8E597EC93221FF19E53EF292C
- generatedChecksum: 85D3482D395C59BDFF268B01940CDDDE
  logicalPath: config\pic32cm_jh01_curiosity_pro
  name: device_cache.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 85D3482D395C59BDFF268B01940CDDDE
- generatedChecksum: E0542F2FF93ECC116DD24DA7B7F5E018
  logicalPath: packs\PIC32CM5164JH01100_DFP\component
  name: divas.h
  physicalPath: ..\..\packs\PIC32CM5164JH01100_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: E0542F2FF93ECC116DD24DA7B7F5E018
- generatedChecksum: CB78AA44B9DC7CDD3A4FE59A639A5B80
  logicalPath: packs\PIC32CM5164JH01100_DFP\component
  name: dmac.h
  physicalPath: ..\..\packs\PIC32CM5164JH01100_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: CB78AA44B9DC7CDD3A4FE59A639A5B80
- generatedChecksum: 49BD966379F3155B844B4B608BD67E88
  logicalPath: packs\PIC32CM5164JH01100_DFP\component
  name: dsu.h
  physicalPath: ..\..\packs\PIC32CM5164JH01100_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 49BD966379F3155B844B4B608BD67E88
- generatedChecksum: 217CBD84DE1369172EA641EFF1D74ED6
  logicalPath: packs\PIC32CM5164JH01100_DFP\component
  name: eic.h
  physicalPath: ..\..\packs\PIC32CM5164JH01100_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 217CBD84DE1369172EA641EFF1D74ED6
- generatedChecksum: 49ECE1055006DADB83203309AB452330
  logicalPath: packs\PIC32CM5164JH01100_DFP\component
  name: evsys.h
  physicalPath: ..\..\packs\PIC32CM5164JH01100_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 49ECE1055006DADB83203309AB452330
- generatedChecksum: C54DA5E7970ACFB2ED34949DB2293A4B
  logicalPath: packs\PIC32CM5164JH01100_DFP\component
  name: freqm.h
  physicalPath: ..\..\packs\PIC32CM5164JH01100_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: C54DA5E7970ACFB2ED34949DB2293A4B
- generatedChecksum: 0510B9DBEA69146AD8E9B334DA4C76C3
  logicalPath: packs\PIC32CM5164JH01100_DFP\component
  name: gclk.h
  physicalPath: ..\..\packs\PIC32CM5164JH01100_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 0510B9DBEA69146AD8E9B334DA4C76C3
- generatedChecksum: 1E2AE2A846B9D7C9FFB05AEDF8F9693C
  logicalPath: packs\PIC32CM5164JH01100_DFP\component
  name: icm.h
  physicalPath: ..\..\packs\PIC32CM5164JH01100_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 1E2AE2A846B9D7C9FFB05AEDF8F9693C
- generatedChecksum: 74FBB0B0086481FF14ABBB81469EDDAF
  logicalPath: packs\PIC32CM5164JH01100_DFP\component
  name: mclk.h
  physicalPath: ..\..\packs\PIC32CM5164JH01100_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 74FBB0B0086481FF14ABBB81469EDDAF
- generatedChecksum: 1A5F540E90AE3D3E270607C23ED4BEAE
  logicalPath: packs\PIC32CM5164JH01100_DFP\component
  name: mcramc.h
  physicalPath: ..\..\packs\PIC32CM5164JH01100_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 1A5F540E90AE3D3E270607C23ED4BEAE
- generatedChecksum: B96ADDA2C111E73B26EBA5E7B4498912
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: mpu_armv7.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: B96ADDA2C111E73B26EBA5E7B4498912
- generatedChecksum: FA5E10AD59C1A9BE26A6DA0D119A5DF2
  logicalPath: packs\PIC32CM5164JH01100_DFP\component
  name: mtb.h
  physicalPath: ..\..\packs\PIC32CM5164JH01100_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: FA5E10AD59C1A9BE26A6DA0D119A5DF2
- generatedChecksum: E2043245B15EAE0B0FB3E17555A8ED5D
  logicalPath: packs\PIC32CM5164JH01100_DFP\component
  name: nvmctrl.h
  physicalPath: ..\..\packs\PIC32CM5164JH01100_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: E2043245B15EAE0B0FB3E17555A8ED5D
- generatedChecksum: 13ECDF0F13DFDFB31F668FF2A659644D
  logicalPath: packs\PIC32CM5164JH01100_DFP\component
  name: osc32kctrl.h
  physicalPath: ..\..\packs\PIC32CM5164JH01100_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 13ECDF0F13DFDFB31F668FF2A659644D
- generatedChecksum: 66F3E80798D460A079791D9CC9563B6F
  logicalPath: packs\PIC32CM5164JH01100_DFP\component
  name: oscctrl.h
  physicalPath: ..\..\packs\PIC32CM5164JH01100_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 66F3E80798D460A079791D9CC9563B6F
- generatedChecksum: E95B37FAD3E3F8E283771798C7ED40F4
  logicalPath: packs\PIC32CM5164JH01100_DFP\component
  name: pac.h
  physicalPath: ..\..\packs\PIC32CM5164JH01100_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: E95B37FAD3E3F8E283771798C7ED40F4
- generatedChecksum: FD39F4DC235D816D1B1C2A92D49FC328
  logicalPath: packs\PIC32CM5164JH01100_DFP\component
  name: pdec.h
  physicalPath: ..\..\packs\PIC32CM5164JH01100_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: FD39F4DC235D816D1B1C2A92D49FC328
- generatedChecksum: 0AA8021D00ED4372B5BABF866075BDA4
  logicalPath: packs\PIC32CM5164JH01100_DFP
  name: pic32cm5164jh01100.h
  physicalPath: ..\..\packs\PIC32CM5164JH01100_DFP
  security: NON_SECURE
  type: HEADER
  userChecksum: 0AA8021D00ED4372B5BABF866075BDA4
- generatedChecksum: B3AF2316928ED60BF99915186A5B9871
  logicalPath: packs\PIC32CM5164JH01100_DFP\pio
  name: pic32cm5164jh01100.h
  physicalPath: ..\..\packs\PIC32CM5164JH01100_DFP\pio
  security: NON_SECURE
  type: HEADER
  userChecksum: B3AF2316928ED60BF99915186A5B9871
- generatedChecksum: 0416F129713FDF989ACC1FC57065125C
  logicalPath: config\pic32cm_jh01_curiosity_pro\peripheral\clock
  name: plib_clock.h
  physicalPath: peripheral\clock
  security: NON_SECURE
  type: HEADER
  userChecksum: 0416F129713FDF989ACC1FC57065125C
- generatedChecksum: CCAEF942C66AF995876DFD85CEFF611F
  logicalPath: config\pic32cm_jh01_curiosity_pro\peripheral\evsys
  name: plib_evsys.h
  physicalPath: peripheral\evsys
  security: NON_SECURE
  type: HEADER
  userChecksum: CCAEF942C66AF995876DFD85CEFF611F
- generatedChecksum: E95AB23B866AA0CE6F0ABF637E9E2C83
  logicalPath: config\pic32cm_jh01_curiosity_pro\peripheral\nvic
  name: plib_nvic.h
  physicalPath: peripheral\nvic
  security: NON_SECURE
  type: HEADER
  userChecksum: E95AB23B866AA0CE6F0ABF637E9E2C83
- generatedChecksum: 4F7FEBF22339EDD5572B587F6773DF48
  logicalPath: config\pic32cm_jh01_curiosity_pro\peripheral\nvmctrl
  name: plib_nvmctrl.h
  physicalPath: peripheral\nvmctrl
  security: NON_SECURE
  type: HEADER
  userChecksum: 4F7FEBF22339EDD5572B587F6773DF48
- generatedChecksum: 5A921063FE5AEA1800C063F6C039907B
  logicalPath: config\pic32cm_jh01_curiosity_pro\peripheral\port
  name: plib_port.h
  physicalPath: peripheral\port
  security: NON_SECURE
  type: HEADER
  userChecksum: 5A921063FE5AEA1800C063F6C039907B
- generatedChecksum: 836D6A8A79834B231BEE1A6A092D730A
  logicalPath: config\pic32cm_jh01_curiosity_pro\peripheral\sercom\usart
  name: plib_sercom4_usart.h
  physicalPath: peripheral\sercom\usart
  security: NON_SECURE
  type: HEADER
  userChecksum: 836D6A8A79834B231BEE1A6A092D730A
- generatedChecksum: 60AC1E58C56C00111C35512E0C9AC899
  logicalPath: config\pic32cm_jh01_curiosity_pro\peripheral\sercom\usart
  name: plib_sercom_usart_common.h
  physicalPath: peripheral\sercom\usart
  security: NON_SECURE
  type: HEADER
  userChecksum: 60AC1E58C56C00111C35512E0C9AC899
- generatedChecksum: BAD582053978FFE431EAF9C2BD4C026D
  logicalPath: config\pic32cm_jh01_curiosity_pro\peripheral\systick
  name: plib_systick.h
  physicalPath: peripheral\systick
  security: NON_SECURE
  type: HEADER
  userChecksum: BAD582053978FFE431EAF9C2BD4C026D
- generatedChecksum: 9B1CFBCA32068AE448D4F2A6E6FE74E2
  logicalPath: packs\PIC32CM5164JH01100_DFP\component
  name: pm.h
  physicalPath: ..\..\packs\PIC32CM5164JH01100_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 9B1CFBCA32068AE448D4F2A6E6FE74E2
- generatedChecksum: DE940EA15E7DB8AF310A582E2AE33C2D
  logicalPath: packs\PIC32CM5164JH01100_DFP\component
  name: port.h
  physicalPath: ..\..\packs\PIC32CM5164JH01100_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: DE940EA15E7DB8AF310A582E2AE33C2D
- generatedChecksum: 6B4EAB6B8C0F21C73B08DE79E7AD4580
  logicalPath: packs\PIC32CM5164JH01100_DFP\component
  name: ptc.h
  physicalPath: ..\..\packs\PIC32CM5164JH01100_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 6B4EAB6B8C0F21C73B08DE79E7AD4580
- generatedChecksum: 1AA1869C49FB9BCAD2EF3F5F8FFFD039
  logicalPath: packs\PIC32CM5164JH01100_DFP\component
  name: rstc.h
  physicalPath: ..\..\packs\PIC32CM5164JH01100_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 1AA1869C49FB9BCAD2EF3F5F8FFFD039
- generatedChecksum: DBC420E62EA8A8625AD48F76796FE0D2
  logicalPath: packs\PIC32CM5164JH01100_DFP\component
  name: rtc.h
  physicalPath: ..\..\packs\PIC32CM5164JH01100_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: DBC420E62EA8A8625AD48F76796FE0D2
- generatedChecksum: E501D8221E2993EDC2F9650D219981DF
  logicalPath: packs\PIC32CM5164JH01100_DFP\component
  name: sercom.h
  physicalPath: ..\..\packs\PIC32CM5164JH01100_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: E501D8221E2993EDC2F9650D219981DF
- generatedChecksum: D7D780B7D5A7AF034C9B8D9FFD929E09
  logicalPath: packs\PIC32CM5164JH01100_DFP\component
  name: smbist.h
  physicalPath: ..\..\packs\PIC32CM5164JH01100_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: D7D780B7D5A7AF034C9B8D9FFD929E09
- generatedChecksum: 7365B82B84FB28E37C193EA89AD05E80
  logicalPath: packs\PIC32CM5164JH01100_DFP\component
  name: supc.h
  physicalPath: ..\..\packs\PIC32CM5164JH01100_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 7365B82B84FB28E37C193EA89AD05E80
- generatedChecksum: 3D5C9B84FEA2F3BFBBB280E10EF53C49
  logicalPath: packs\PIC32CM5164JH01100_DFP\component
  name: tc.h
  physicalPath: ..\..\packs\PIC32CM5164JH01100_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 3D5C9B84FEA2F3BFBBB280E10EF53C49
- generatedChecksum: 532A47CE0212074C9E17F2EC421EC354
  logicalPath: packs\PIC32CM5164JH01100_DFP\component
  name: tcc.h
  physicalPath: ..\..\packs\PIC32CM5164JH01100_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 532A47CE0212074C9E17F2EC421EC354
- generatedChecksum: 20E829A99B86C2889E4E2E536161C27A
  logicalPath: config\pic32cm_jh01_curiosity_pro
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 20E829A99B86C2889E4E2E536161C27A
- generatedChecksum: 20E16E3F8B38233B6E956128E817F794
  logicalPath: packs\PIC32CM5164JH01100_DFP\component
  name: wdt.h
  physicalPath: ..\..\packs\PIC32CM5164JH01100_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 20E16E3F8B38233B6E956128E817F794
- generatedChecksum: 06918054146968585EE49ADA6FC619BC
  logicalPath: config\pic32cm_jh01_curiosity_pro
  name: PIC32CM5164JH01100.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 06918054146968585EE49ADA6FC619BC
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32cm_jh01_curiosity_pro;../src/packs/PIC32CM5164JH01100_DFP;../src/packs/CMSIS/CMSIS/Core/Include;../src/packs/CMSIS/
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32cm_jh01_curiosity_pro;../src/packs/PIC32CM5164JH01100_DFP;../src/packs/CMSIS/CMSIS/Core/Include;../src/packs/CMSIS/
sourcePaths: []
